version: '1'
services:
  caddy:
    container_name: caddy
    profiles: ["caddy"]
    build: ./frontend
    environment:
      PORT: 3000
      LOG_LEVEL: info
      DASHBOARD: onroutebc-prod-frontend.apps.gold.devops.gov.bc.ca
    ports: ["3000:3000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
# not supported in older versions   
#   post_start:
#      command: sed -i "s/{{HOSTNAME}}/${HOSTNAME}/g" /var/www/onroute/index.html
