version: '1'
services:
  caddy:
    container_name: caddy
    profiles: ["caddy"]
    build: ./frontend
    environment:
      PORT: 3000
      LOG_LEVEL: info
    ports: ["3000:3000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
