---
name: Deploy Uat (Gold)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "latest"
      params:
        description: 'Extra parameters to pass to helm upgrade'
        default: ''
        required: false
        type: string
  workflow_call:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "latest"
      params:
        description: 'Extra parameters to pass to helm upgrade'
        default: ''
        required: false
        type: string
jobs:
  deploys-gold-uat:
    name: Deploys (${{ github.event.number }})
    uses: ./.github/workflows/.deployer.yml
    secrets: inherit
    with:
      environment: gold-uat
      tag: ${{ inputs.tag }}
      params:
        --set frontend.ingress.host="uat.onroutebc.gov.bc.ca"
        --set frontend.ingress.tls.secretName=uat-tls
        ${{ inputs.params }}

  deploys-golddr-uat:
    name: Deploys (${{ github.event.number }})
    uses: ./.github/workflows/.deployer.yml
    secrets: inherit
    with:
      environment: golddr-uat
      tag: ${{ inputs.tag }}
      params:
        --set frontend.ingress.host="uat.onroutebc.gov.bc.ca"
        --set frontend.ingress.tls.secretName=uat-tls
        ${{ inputs.params }} 

