---
name: Deploy Demo (Silver)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "latest"
      params:
        description: 'Extra parameters to pass to helm upgrade'
        default: ''
        required: false
        type: string
  workflow_call:
    inputs:
      tag:
        description: "Image tag to deploy"
        required: false
        type: string
        default: "latest"
      params:
        description: 'Extra parameters to pass to helm upgrade'
        default: ''
        required: false
        type: string
jobs:
  deploys-silver-demo:
    name: Deploys (${{ github.event.number }})
    uses: ./.github/workflows/.deployer.yml
    secrets: inherit
    with:
      environment: silver-demo
      tag: ${{ needs.vars.outputs.tag }}
      params:
        --set global.domain="apps.silver.devops.gov.bc.ca"
        ${{ inputs.params }}
